smplx_models: "/local/home/cormond/SMPL2AddBiomechanics/models/"
# skel_models: "/local/home/cormond/SMPL2AddBiomechanics/models/bsm"
skel_models : "/local/home/cormond/SMPL2AddBiomechanics/models/bsm/"
